modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/astarivi/AstarMobs/issues"
license = "GPL-3.0-or-later"

[[mods]]
modId = "astarmobs"
version = "${version}"
displayName = "Astar Mobs"
authors = "astarivi, Monomaximo"
description = '''
Adds diverse animals with unique behaviors, making your world feel more alive
'''
logoFile = "assets/astarmobs/icon.png"

[[dependencies.astarmobs]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.astarmobs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.astarmobs]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.astarmobs]]
modId = "geckolib"
type = "required"
versionRange = "[4.8.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "astarmobs.mixins.json"
